### PR TITLE
Adding some missing Palestine universities

### PR DESCRIPTION
**Pull request by ScSherifTarek**
Adding some missing universities and institutes including:

1.  gaza and israa universities in palestine
2.  bethlehem bible college to palestine universities
3.  Dar Al-Kalima University College of Arts and Culture to Palestine Universities
4. Ibrahimieh College
5.  Edward Said National Conservatory of Music in Palestine Universities
6.  Applied Research Institute Jerusalem and International Academy of Art Palestine in palestine universities
7.  Health, Development, Information and Policy Institute to Palestine universities
8.  Palestinian Academic Network
9.  Palestinian Academic Society for the Study of International Affairs to Palestine Universities

### CODE REVIEW

**Comment by Omranic** [comment]
@ScSherifTarek  thank you for this PR:
- This branch has conflicts that must be resolved, would you kindly fix it first

**Comment by ScSherifTarek** [comment]
@Omranic 
I was missing two commas in the file names.json and there was two wrong wrote tests, one for opening file the path was not correct and one for the number of universities in Egypt as some universities have been added.

**Comment by Omranic** [comment]
This branch still has conflicts that must be resolved..

**Comment by ScSherifTarek** [comment]
@Omranic 
Now all is fine.

**Comment by Omranic** [comment]
@ScSherifTarek thank you, would you kindly compress JSON files please (uglify) .. once done, will merge this PR

**Pull request merged**
